package bean;
// Generated 08/10/2025 11:02:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CearVendedor generated by hbm2java
 */
@Entity
@Table(name="cear_vendedor"
    ,catalog="db_celso_ramos"
)
public class CearVendedor  implements java.io.Serializable {


     private int cearIdVendedor;
     private String cearNome;
     private String cearCpf;
     private String cearTelefone;
     private String cearEmail;
     private Date cearDataContratacao;
     private BigDecimal cearSalario;
     private String cearAtivo;
     private Set cearVendases = new HashSet(0);

    public CearVendedor() {
    }

	
    public CearVendedor(int cearIdVendedor, String cearNome, String cearCpf, String cearTelefone, String cearEmail, Date cearDataContratacao, BigDecimal cearSalario, String cearAtivo) {
        this.cearIdVendedor = cearIdVendedor;
        this.cearNome = cearNome;
        this.cearCpf = cearCpf;
        this.cearTelefone = cearTelefone;
        this.cearEmail = cearEmail;
        this.cearDataContratacao = cearDataContratacao;
        this.cearSalario = cearSalario;
        this.cearAtivo = cearAtivo;
    }
    public CearVendedor(int cearIdVendedor, String cearNome, String cearCpf, String cearTelefone, String cearEmail, Date cearDataContratacao, BigDecimal cearSalario, String cearAtivo, Set cearVendases) {
       this.cearIdVendedor = cearIdVendedor;
       this.cearNome = cearNome;
       this.cearCpf = cearCpf;
       this.cearTelefone = cearTelefone;
       this.cearEmail = cearEmail;
       this.cearDataContratacao = cearDataContratacao;
       this.cearSalario = cearSalario;
       this.cearAtivo = cearAtivo;
       this.cearVendases = cearVendases;
    }
   
     @Id 

    
    @Column(name="cear_id_vendedor", unique=true, nullable=false)
    public int getCearIdVendedor() {
        return this.cearIdVendedor;
    }
    
    public void setCearIdVendedor(int cearIdVendedor) {
        this.cearIdVendedor = cearIdVendedor;
    }

    
    @Column(name="cear_nome", nullable=false, length=40)
    public String getCearNome() {
        return this.cearNome;
    }
    
    public void setCearNome(String cearNome) {
        this.cearNome = cearNome;
    }

    
    @Column(name="cear_cpf", nullable=false, length=14)
    public String getCearCpf() {
        return this.cearCpf;
    }
    
    public void setCearCpf(String cearCpf) {
        this.cearCpf = cearCpf;
    }

    
    @Column(name="cear_telefone", nullable=false, length=20)
    public String getCearTelefone() {
        return this.cearTelefone;
    }
    
    public void setCearTelefone(String cearTelefone) {
        this.cearTelefone = cearTelefone;
    }

    
    @Column(name="cear_email", nullable=false, length=30)
    public String getCearEmail() {
        return this.cearEmail;
    }
    
    public void setCearEmail(String cearEmail) {
        this.cearEmail = cearEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cear_data_contratacao", nullable=false, length=10)
    public Date getCearDataContratacao() {
        return this.cearDataContratacao;
    }
    
    public void setCearDataContratacao(Date cearDataContratacao) {
        this.cearDataContratacao = cearDataContratacao;
    }

    
    @Column(name="cear_salario", nullable=false, precision=10)
    public BigDecimal getCearSalario() {
        return this.cearSalario;
    }
    
    public void setCearSalario(BigDecimal cearSalario) {
        this.cearSalario = cearSalario;
    }

    
    @Column(name="cear_ativo", nullable=false, length=1)
    public String getCearAtivo() {
        return this.cearAtivo;
    }
    
    public void setCearAtivo(String cearAtivo) {
        this.cearAtivo = cearAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cearVendedor")
    public Set getCearVendases() {
        return this.cearVendases;
    }
    
    public void setCearVendases(Set cearVendases) {
        this.cearVendases = cearVendases;
    }




}


