package bean;
// Generated 08/10/2025 11:02:44 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CearVendasprodutos generated by hbm2java
 */
@Entity
@Table(name="cear_vendasprodutos"
    ,catalog="db_celso_ramos"
)
public class CearVendasprodutos  implements java.io.Serializable {


     private int cearIdVendasprodutos;
     private CearProdutos cearProdutos;
     private CearVendas cearVendas;
     private int cearQuantidade;
     private double cearValorunitario;

    public CearVendasprodutos() {
    }

    public CearVendasprodutos(int cearIdVendasprodutos, CearProdutos cearProdutos, CearVendas cearVendas, int cearQuantidade, double cearValorunitario) {
       this.cearIdVendasprodutos = cearIdVendasprodutos;
       this.cearProdutos = cearProdutos;
       this.cearVendas = cearVendas;
       this.cearQuantidade = cearQuantidade;
       this.cearValorunitario = cearValorunitario;
    }
   
     @Id 

    
    @Column(name="cear_id_vendasprodutos", unique=true, nullable=false)
    public int getCearIdVendasprodutos() {
        return this.cearIdVendasprodutos;
    }
    
    public void setCearIdVendasprodutos(int cearIdVendasprodutos) {
        this.cearIdVendasprodutos = cearIdVendasprodutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cear_fk_produtos", nullable=false)
    public CearProdutos getCearProdutos() {
        return this.cearProdutos;
    }
    
    public void setCearProdutos(CearProdutos cearProdutos) {
        this.cearProdutos = cearProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cear_fk_vendas", nullable=false)
    public CearVendas getCearVendas() {
        return this.cearVendas;
    }
    
    public void setCearVendas(CearVendas cearVendas) {
        this.cearVendas = cearVendas;
    }

    
    @Column(name="cear_quantidade", nullable=false)
    public int getCearQuantidade() {
        return this.cearQuantidade;
    }
    
    public void setCearQuantidade(int cearQuantidade) {
        this.cearQuantidade = cearQuantidade;
    }

    
    @Column(name="cear_valorunitario", nullable=false, precision=10)
    public double getCearValorunitario() {
        return this.cearValorunitario;
    }
    
    public void setCearValorunitario(double cearValorunitario) {
        this.cearValorunitario = cearValorunitario;
    }




}


