package bean;
// Generated 08/10/2025 11:02:44 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * CearUsuarios generated by hbm2java
 */
@Entity
@Table(name="cear_usuarios"
    ,catalog="db_celso_ramos"
)
public class CearUsuarios  implements java.io.Serializable {


     private int cearIdUsuarios;
     private String cearNome;
     private String cearApelido;
     private String cearCpf;
     private Date cearDataNascimento;
     private String cearSenha;
     private int cearNivel;
     private String cearAtivo;

    public CearUsuarios() {
    }

    public CearUsuarios(int cearIdUsuarios, String cearNome, String cearApelido, String cearCpf, Date cearDataNascimento, String cearSenha, int cearNivel, String cearAtivo) {
       this.cearIdUsuarios = cearIdUsuarios;
       this.cearNome = cearNome;
       this.cearApelido = cearApelido;
       this.cearCpf = cearCpf;
       this.cearDataNascimento = cearDataNascimento;
       this.cearSenha = cearSenha;
       this.cearNivel = cearNivel;
       this.cearAtivo = cearAtivo;
    }
   
     @Id 

    
    @Column(name="cear_id_usuarios", unique=true, nullable=false)
    public int getCearIdUsuarios() {
        return this.cearIdUsuarios;
    }
    
    public void setCearIdUsuarios(int cearIdUsuarios) {
        this.cearIdUsuarios = cearIdUsuarios;
    }

    
    @Column(name="cear_nome", nullable=false, length=45)
    public String getCearNome() {
        return this.cearNome;
    }
    
    public void setCearNome(String cearNome) {
        this.cearNome = cearNome;
    }

    
    @Column(name="cear_apelido", nullable=false, length=25)
    public String getCearApelido() {
        return this.cearApelido;
    }
    
    public void setCearApelido(String cearApelido) {
        this.cearApelido = cearApelido;
    }

    
    @Column(name="cear_cpf", nullable=false, length=14)
    public String getCearCpf() {
        return this.cearCpf;
    }
    
    public void setCearCpf(String cearCpf) {
        this.cearCpf = cearCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cear_data_nascimento", nullable=false, length=10)
    public Date getCearDataNascimento() {
        return this.cearDataNascimento;
    }
    
    public void setCearDataNascimento(Date cearDataNascimento) {
        this.cearDataNascimento = cearDataNascimento;
    }

    
    @Column(name="cear_senha", nullable=false, length=20)
    public String getCearSenha() {
        return this.cearSenha;
    }
    
    public void setCearSenha(String cearSenha) {
        this.cearSenha = cearSenha;
    }

    
    @Column(name="cear_nivel", nullable=false)
    public int getCearNivel() {
        return this.cearNivel;
    }
    
    public void setCearNivel(int cearNivel) {
        this.cearNivel = cearNivel;
    }

    
    @Column(name="cear_ativo", nullable=false, length=1)
    public String getCearAtivo() {
        return this.cearAtivo;
    }
    
    public void setCearAtivo(String cearAtivo) {
        this.cearAtivo = cearAtivo;
    }


}


