package bean;
// Generated 08/10/2025 11:02:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CearProdutos generated by hbm2java
 */
@Entity
@Table(name="cear_produtos"
    ,catalog="db_celso_ramos"
)
public class CearProdutos  implements java.io.Serializable {


     private int cearIdProdutos;
     private Date cearDataLancamento;
     private BigDecimal cearValor;
     private String cearMarca;
     private String cearNome;
     private int cearModelo;
     private Date cearDataFabricacao;
     private String cearUsado;
     private Set cearVendasprodutoses = new HashSet(0);

    public CearProdutos() {
    }

	
    public CearProdutos(int cearIdProdutos, Date cearDataLancamento, BigDecimal cearValor, String cearMarca, String cearNome, int cearModelo, Date cearDataFabricacao, String cearUsado) {
        this.cearIdProdutos = cearIdProdutos;
        this.cearDataLancamento = cearDataLancamento;
        this.cearValor = cearValor;
        this.cearMarca = cearMarca;
        this.cearNome = cearNome;
        this.cearModelo = cearModelo;
        this.cearDataFabricacao = cearDataFabricacao;
        this.cearUsado = cearUsado;
    }
    public CearProdutos(int cearIdProdutos, Date cearDataLancamento, BigDecimal cearValor, String cearMarca, String cearNome, int cearModelo, Date cearDataFabricacao, String cearUsado, Set cearVendasprodutoses) {
       this.cearIdProdutos = cearIdProdutos;
       this.cearDataLancamento = cearDataLancamento;
       this.cearValor = cearValor;
       this.cearMarca = cearMarca;
       this.cearNome = cearNome;
       this.cearModelo = cearModelo;
       this.cearDataFabricacao = cearDataFabricacao;
       this.cearUsado = cearUsado;
       this.cearVendasprodutoses = cearVendasprodutoses;
    }
   
     @Id 

    
    @Column(name="cear_id_produtos", unique=true, nullable=false)
    public int getCearIdProdutos() {
        return this.cearIdProdutos;
    }
    
    public void setCearIdProdutos(int cearIdProdutos) {
        this.cearIdProdutos = cearIdProdutos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cear_data_lancamento", nullable=false, length=10)
    public Date getCearDataLancamento() {
        return this.cearDataLancamento;
    }
    
    public void setCearDataLancamento(Date cearDataLancamento) {
        this.cearDataLancamento = cearDataLancamento;
    }

    
    @Column(name="cear_valor", nullable=false, precision=10)
    public BigDecimal getCearValor() {
        return this.cearValor;
    }
    
    public void setCearValor(BigDecimal cearValor) {
        this.cearValor = cearValor;
    }

    
    @Column(name="cear_marca", nullable=false, length=25)
    public String getCearMarca() {
        return this.cearMarca;
    }
    
    public void setCearMarca(String cearMarca) {
        this.cearMarca = cearMarca;
    }

    
    @Column(name="cear_nome", nullable=false, length=30)
    public String getCearNome() {
        return this.cearNome;
    }
    
    public void setCearNome(String cearNome) {
        this.cearNome = cearNome;
    }

    
    @Column(name="cear_modelo", nullable=false)
    public int getCearModelo() {
        return this.cearModelo;
    }
    
    public void setCearModelo(int cearModelo) {
        this.cearModelo = cearModelo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cear_data_fabricacao", nullable=false, length=10)
    public Date getCearDataFabricacao() {
        return this.cearDataFabricacao;
    }
    
    public void setCearDataFabricacao(Date cearDataFabricacao) {
        this.cearDataFabricacao = cearDataFabricacao;
    }

    
    @Column(name="cear_usado", nullable=false, length=1)
    public String getCearUsado() {
        return this.cearUsado;
    }
    
    public void setCearUsado(String cearUsado) {
        this.cearUsado = cearUsado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cearProdutos")
    public Set getCearVendasprodutoses() {
        return this.cearVendasprodutoses;
    }
    
    public void setCearVendasprodutoses(Set cearVendasprodutoses) {
        this.cearVendasprodutoses = cearVendasprodutoses;
    }




}


