package bean;
// Generated 08/10/2025 11:02:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CearClientes generated by hbm2java
 */
@Entity
@Table(name="cear_clientes"
    ,catalog="db_celso_ramos"
)
public class CearClientes  implements java.io.Serializable {


     private int cearIdClientes;
     private String cearNome;
     private String cearCpf;
     private Date cearDataNascimento;
     private String cearEmail;
     private String cearSenha;
     private String cearIdade;
     private String cearRg;
     private String cearNumero;
     private String cearEndereco;
     private String cearSexo;
     private String cearCidade;
     private String cearEstado;
     private String cearTelefone;
     private String cearBairro;


    public CearClientes() {
    }

	
    public CearClientes(int cearIdClientes, String cearNome, String cearCpf, Date cearDataNascimento, String cearEmail, String cearSenha, String cearIdade, String cearRg, String cearNumero, String cearEndereco, String cearSexo, String cearCidade, String cearEstado, String cearTelefone, String cearBairro) {
        this.cearIdClientes = cearIdClientes;
        this.cearNome = cearNome;
        this.cearCpf = cearCpf;
        this.cearDataNascimento = cearDataNascimento;
        this.cearEmail = cearEmail;
        this.cearSenha = cearSenha;
        this.cearIdade = cearIdade;
        this.cearRg = cearRg;
        this.cearNumero = cearNumero;
        this.cearEndereco = cearEndereco;
        this.cearSexo = cearSexo;
        this.cearCidade = cearCidade;
        this.cearEstado = cearEstado;
        this.cearTelefone = cearTelefone;
        this.cearBairro = cearBairro;
    }
    public CearClientes(int cearIdClientes, String cearNome, String cearCpf, Date cearDataNascimento, String cearEmail, String cearSenha, String cearIdade, String cearRg, String cearNumero, String cearEndereco, String cearSexo, String cearCidade, String cearEstado, String cearTelefone, String cearBairro, Set cearVendases) {
       this.cearIdClientes = cearIdClientes;
       this.cearNome = cearNome;
       this.cearCpf = cearCpf;
       this.cearDataNascimento = cearDataNascimento;
       this.cearEmail = cearEmail;
       this.cearSenha = cearSenha;
       this.cearIdade = cearIdade;
       this.cearRg = cearRg;
       this.cearNumero = cearNumero;
       this.cearEndereco = cearEndereco;
       this.cearSexo = cearSexo;
       this.cearCidade = cearCidade;
       this.cearEstado = cearEstado;
       this.cearTelefone = cearTelefone;
       this.cearBairro = cearBairro;
      
    }
   
     @Id 

    
    @Column(name="cear_id_clientes", unique=true, nullable=false)
    public int getCearIdClientes() {
        return this.cearIdClientes;
    }
    
    public void setCearIdClientes(int cearIdClientes) {
        this.cearIdClientes = cearIdClientes;
    }

    
    @Column(name="cear_nome", nullable=false, length=50)
    public String getCearNome() {
        return this.cearNome;
    }
    
    public void setCearNome(String cearNome) {
        this.cearNome = cearNome;
    }

    
    @Column(name="cear_cpf", nullable=false, length=14)
    public String getCearCpf() {
        return this.cearCpf;
    }
    
    public void setCearCpf(String cearCpf) {
        this.cearCpf = cearCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cear_data_nascimento", nullable=false, length=10)
    public Date getCearDataNascimento() {
        return this.cearDataNascimento;
    }
    
    public void setCearDataNascimento(Date cearDataNascimento) {
        this.cearDataNascimento = cearDataNascimento;
    }

    
    @Column(name="cear_email", nullable=false, length=45)
    public String getCearEmail() {
        return this.cearEmail;
    }
    
    public void setCearEmail(String cearEmail) {
        this.cearEmail = cearEmail;
    }

    
    @Column(name="cear_senha", nullable=false, length=50)
    public String getCearSenha() {
        return this.cearSenha;
    }
    
    public void setCearSenha(String cearSenha) {
        this.cearSenha = cearSenha;
    }

    
    @Column(name="cear_idade", nullable=false, length=3)
    public String getCearIdade() {
        return this.cearIdade;
    }
    
    public void setCearIdade(String cearIdade) {
        this.cearIdade = cearIdade;
    }

    
    @Column(name="cear_rg", nullable=false, length=14)
    public String getCearRg() {
        return this.cearRg;
    }
    
    public void setCearRg(String cearRg) {
        this.cearRg = cearRg;
    }

    
    @Column(name="cear_numero", nullable=false, length=20)
    public String getCearNumero() {
        return this.cearNumero;
    }
    
    public void setCearNumero(String cearNumero) {
        this.cearNumero = cearNumero;
    }

    
    @Column(name="cear_endereco", nullable=false, length=150)
    public String getCearEndereco() {
        return this.cearEndereco;
    }
    
    public void setCearEndereco(String cearEndereco) {
        this.cearEndereco = cearEndereco;
    }

    
    @Column(name="cear_sexo", nullable=false, length=1)
    public String getCearSexo() {
        return this.cearSexo;
    }
    
    public void setCearSexo(String cearSexo) {
        this.cearSexo = cearSexo;
    }

    
    @Column(name="cear_cidade", nullable=false, length=50)
    public String getCearCidade() {
        return this.cearCidade;
    }
    
    public void setCearCidade(String cearCidade) {
        this.cearCidade = cearCidade;
    }

    
    @Column(name="cear_estado", nullable=false, length=2)
    public String getCearEstado() {
        return this.cearEstado;
    }
    
    public void setCearEstado(String cearEstado) {
        this.cearEstado = cearEstado;
    }

    
    @Column(name="cear_telefone", nullable=false, length=20)
    public String getCearTelefone() {
        return this.cearTelefone;
    }
    
    public void setCearTelefone(String cearTelefone) {
        this.cearTelefone = cearTelefone;
    }

    
    @Column(name="cear_bairro", nullable=false, length=50)
    public String getCearBairro() {
        return this.cearBairro;
    }
    
    public void setCearBairro(String cearBairro) {
        this.cearBairro = cearBairro;
    }



}


