package bean;
// Generated 08/10/2025 11:02:44 by Hibernate Tools 4.3.1



import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CearVendas generated by hbm2java
 */
@Entity
@Table(name="cear_vendas"
    ,catalog="db_celso_ramos"
)
public class CearVendas  implements java.io.Serializable {


     private int cearIdVendas;
     private CearClientes cearClientes;
     private CearVendedor cearVendedor;
     private Date cearDataVenda;
     private double cearTotal;
     private String cearFormaPagamento;
     

    public CearVendas() {
    }

	
    public CearVendas(int cearIdVendas, CearClientes cearClientes, CearVendedor cearVendedor, Date cearDataVenda, double cearTotal, String cearFormaPagamento) {
        this.cearIdVendas = cearIdVendas;
        this.cearClientes = cearClientes;
        this.cearVendedor = cearVendedor;
        this.cearDataVenda = cearDataVenda;
        this.cearTotal = cearTotal;
        this.cearFormaPagamento = cearFormaPagamento;
    }
    public CearVendas(int cearIdVendas, CearClientes cearClientes, CearVendedor cearVendedor, Date cearDataVenda, double cearTotal, String cearFormaPagamento, Set cearVendasprodutoses) {
       this.cearIdVendas = cearIdVendas;
       this.cearClientes = cearClientes;
       this.cearVendedor = cearVendedor;
       this.cearDataVenda = cearDataVenda;
       this.cearTotal = cearTotal;
       this.cearFormaPagamento = cearFormaPagamento;
     
    }
   
     @Id 

    
    @Column(name="cear_id_vendas", unique=true, nullable=false)
    public int getCearIdVendas() {
        return this.cearIdVendas;
    }
    
    public void setCearIdVendas(int cearIdVendas) {
        this.cearIdVendas = cearIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cear_fk_clientes", nullable=false)
    public CearClientes getCearClientes() {
        return this.cearClientes;
    }
    
    public void setCearClientes(CearClientes cearClientes) {
        this.cearClientes = cearClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cear_fk_vendedor", nullable=false)
    public CearVendedor getCearVendedor() {
        return this.cearVendedor;
    }
    
    public void setCearVendedor(CearVendedor cearVendedor) {
        this.cearVendedor = cearVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cear_data_venda", nullable=false, length=10)
    public Date getCearDataVenda() {
        return this.cearDataVenda;
    }
    
    public void setCearDataVenda(Date cearDataVenda) {
        this.cearDataVenda = cearDataVenda;
    }

    
    @Column(name="cear_total", nullable=false, precision=10)
    public double getCearTotal() {
        return this.cearTotal;
    }
    
    public void setCearTotal(double cearTotal) {
        this.cearTotal = cearTotal;
    }

    
    @Column(name="cear_forma_pagamento", nullable=false, length=5)
    public String getCearFormaPagamento() {
        return this.cearFormaPagamento;
    }
    
    public void setCearFormaPagamento(String cearFormaPagamento) {
        this.cearFormaPagamento = cearFormaPagamento;
    }



}


